### ISSUE TITLE
Running the dc.exe "initial setup" wipes out the user's Path variable on Windows

### ISSUE THREAD

**Issue by forbjok** [mihails-strasuns/dc#20]
Running dc.exe to perform the "initial setup" wipes out the user's Path variable by turning it into `"%PATH%;<dc bin path>"`, causing everything that was previously in the user's Path but not the system-wide Path to be lost on the next login.

**Comment by mihails-strasuns** [comment]
This sounds like a rather awkward bug! 😊 Please check the linked PR, it should fix it (you can download prebuilt binaries from CI)

**Comment by mihails-strasuns** [comment]
https://github.com/mihails-strasuns/dc/releases/tag/v1.0.1

**Comment by forbjok** [comment]
I've tested the new release, and it does not really fix the problem, just change it into a different one. Now it replaces the user's path with what I'm guessing is most of the system-wide path, and also seems to truncate it so that the user's path instead becomes a partial copy of the system-wide path.

You can't replace the user's path with the current process' PATH on Windows, as it has two separate PATH variables - one for the user and one for the whole system that will contain separate entries and be merged in the actual process PATH environment variable seen by processes. In order for it to work correctly, it must only append the new path to the user's PATH variable without overwriting it with anything from the active process PATH.

**Comment by mihails-strasuns** [comment]
I see. Do you know what is the correct way on Windows to get just the user path value? I have very little knowledge of Windows myself, sadly.

**Comment by forbjok** [comment]
From what I can find, using the setx command to update the PATH isn't safe even if you pass it the user's PATH variable, as it will cause environment variables in the current PATH string to get expanded as well.
There may be some Win32 API function for doing it that is more appropriate, but from what I can quickly find it seems like the easiest way to do it would be to just modify the registry value HKEY_CURRENT_USER\Environment\Path directly and append it.

I don't have any code examples of how to do this in D, but I imagine it should be possible to call the Win32 registry functions. https://docs.microsoft.com/en-us/windows/desktop/SysInfo/registry-functions

**Comment by mihails-strasuns** [comment]
Thanks, will give it a try.

**Comment by mihails-strasuns** [comment]
Does https://github.com/mihails-strasuns/dc/pull/23 work better?

**Comment by forbjok** [comment]
Yep, seems to work correctly now.
